name: "deploy"
on:
  push:
    branches:
      - master
      - fixup-deploy
env:
  CI: 1
  RUST_BACKTRACE: full
  RUSTC_BOOTSTRAP: 1
  DOCKER_BUILDKIT: 1
jobs:
  docker:
    name: docker
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2
      - name: Build invoker
        run: |
          docker build -t ghcr.io/jjs-dev/jjs-invoker:latest .
      - name: Upload images
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/jjs-dev/jjs-invoker:latest
