---
name: deploy
"on":
  push:
    branches:
      - master
      - trying
      - fixup-deploy
env:
  DOCKER_BUILDKIT: 1
jobs:
  docker:
    name: docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build invoker
        run: "bash build.sh --release\n"
      - name: Upload images
        run: "if [ \"$GITHUB_REF\" = \"refs/heads/master\" ] || [ \"$GITHUB_REF\" = \"refs/heads/fixup-deploy\" ]\nthen\n  TAG=\"latest\"\nelif [ \"$GITHUB_REF\" = \"refs/heads/trying\" ]\nthen\n  TAG=\"trying\"\nelse\n  echo \"unknown GITHUB_REF: $GITHUB_REF\"\n  exit 1\nfi\n\ndocker tag jjs-invoker ghcr.io/jjs-dev/jjs-invoker:$TAG\necho ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin\ndocker push ghcr.io/jjs-dev/jjs-invoker:$TAG\n"